# main2.yml
---

- name: Begin Patching
  hosts: all
  remote_user: vagrant
  become: true
#  tasks:
#  - name: say hi
#    tags: foo
#    shell: echo "hi..."


- import_playbook: playbooks/rest_post.yml status="Checking host service" astatus="Checking host service" percent=1
- import_playbook: playbooks/service_status.yml
  vars:
    service_list: [ crond ]

# Pre host checks
#- import_playbook: playbooks/cs-precheck.yml

- import_playbook: playbooks/rest_post.yml status="Downloading Patches" astatus="Downloading Patches" percent=10
- import_playbook: playbooks/patching-download-only.yml

- import_playbook: playbooks/rest_post.yml status="Stopping critical services" astatus="Stopping critical services" percent=25
- import_playbook: playbooks/service_state.yml
  vars:
    service_state: started
    service_list: [ crond ]

- import_playbook: playbooks/rest_post.yml status="Patching and rebooting host" astatus="Patching and rebooting host" percent=50
#- import_playbook: playbooks/patching.yml
- import_playbook: playbooks/patching.yml reboot_host=false reboot_when_needed=true
- import_playbook: playbooks/rest_post.yml status="Patching and rebooting host" astatus="Patching and rebooting host" percent=75

- import_playbook: playbooks/rest_post.yml status="Checking host service" astatus="Checking host service" percent=99
- import_playbook: playbooks/service_status.yml
  vars:
    service_list: [ crond ]

- import_playbook: playbooks/rest_post.yml status="Rebooted" astatus="Rebooted" percent=100
